-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema POS_SYSTEM
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema POS_SYSTEM
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `POS_SYSTEM` DEFAULT CHARACTER SET utf8 ;
USE `POS_SYSTEM` ;

-- -----------------------------------------------------
-- Table `POS_SYSTEM`.`PERSONNEL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `POS_SYSTEM`.`PERSONNEL` (
  `PER_TYPE` INT NOT NULL,
  `PER_FNAME` VARCHAR(45) NOT NULL,
  `PER_LNAME` VARCHAR(45) NOT NULL,
  `PER_ADDR` VARCHAR(45) NOT NULL,
  `PER_DOB` DATETIME NOT NULL,
  PRIMARY KEY (`PER_TYPE`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `POS_SYSTEM`.`CUSTOMER(S)`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `POS_SYSTEM`.`CUSTOMER(S)` (
  `PERSONNEL_PER_TYPE` INT NOT NULL,
  `CUSTOMER_PAY` DECIMAL(4) NOT NULL,
  PRIMARY KEY (`PERSONNEL_PER_TYPE`),
  CONSTRAINT `fk_CUSTOMER(S)_PERSONNEL1`
    FOREIGN KEY (`PERSONNEL_PER_TYPE`)
    REFERENCES `POS_SYSTEM`.`PERSONNEL` (`PER_TYPE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `POS_SYSTEM`.`BAR_MENU`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `POS_SYSTEM`.`BAR_MENU` (
  `DRINK_NAME` VARCHAR(45) NOT NULL,
  `DRINK_INGREDIENT` VARCHAR(45) NOT NULL,
  `DRINK_PRICE` VARCHAR(45) NOT NULL,
  `DRINK_SPECIALTY` VARCHAR(45) NOT NULL,
  `DRINK_WINE_SELECTION` VARCHAR(45) NOT NULL,
  `DRINK_BEER` VARCHAR(45) NOT NULL,
  `DRINK_RUM` VARCHAR(45) NOT NULL,
  `CUSTOMER(S)_PERSONNEL_PER_TYPE` INT NOT NULL,
  PRIMARY KEY (`DRINK_NAME`, `CUSTOMER(S)_PERSONNEL_PER_TYPE`),
  INDEX `fk_BAR_MENU_CUSTOMER(S)1_idx` (`CUSTOMER(S)_PERSONNEL_PER_TYPE` ASC) VISIBLE,
  CONSTRAINT `fk_BAR_MENU_CUSTOMER(S)1`
    FOREIGN KEY (`CUSTOMER(S)_PERSONNEL_PER_TYPE`)
    REFERENCES `POS_SYSTEM`.`CUSTOMER(S)` (`PERSONNEL_PER_TYPE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `POS_SYSTEM`.`BARTENDER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `POS_SYSTEM`.`BARTENDER` (
  `PERSONNEL_PER_TYPE` INT NOT NULL,
  `BAR_JOB_DESC` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`PERSONNEL_PER_TYPE`),
  CONSTRAINT `fk_BARTENDER_PERSONNEL1`
    FOREIGN KEY (`PERSONNEL_PER_TYPE`)
    REFERENCES `POS_SYSTEM`.`PERSONNEL` (`PER_TYPE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `POS_SYSTEM`.`PRINT_INVOICE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `POS_SYSTEM`.`PRINT_INVOICE` (
  `INVOICE_ID` INT NOT NULL,
  `INVOICE_DATE` DATETIME(12) NOT NULL,
  `INVOICE_TOTAL` DECIMAL(4) NOT NULL,
  PRIMARY KEY (`INVOICE_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `POS_SYSTEM`.`POS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `POS_SYSTEM`.`POS` (
  `POS_ID` INT NOT NULL,
  `BAR_PRODUCTS_DRINK_ID` INT NOT NULL,
  `TIME_OF_WORK` INT NOT NULL,
  `LOGOUT` VARCHAR(45) NOT NULL,
  `CUSTOMER(S)_PERSONNEL_PER_TYPE` INT NOT NULL,
  `BARTENDER_PERSONNEL_PER_TYPE` INT NOT NULL,
  `PRINT_INVOICE_INVOICE_ID` INT NOT NULL,
  `POS_DRINKS` VARCHAR(45) NOT NULL,
  `POS_PRICES` INT NOT NULL,
  `POS_TAX` INT NOT NULL,
  `POS_TIPS` INT NOT NULL,
  `POS_TOTAL` INT NOT NULL,
  PRIMARY KEY (`POS_ID`, `BAR_PRODUCTS_DRINK_ID`, `CUSTOMER(S)_PERSONNEL_PER_TYPE`, `BARTENDER_PERSONNEL_PER_TYPE`, `PRINT_INVOICE_INVOICE_ID`),
  INDEX `fk_POS_CUSTOMER(S)1_idx` (`CUSTOMER(S)_PERSONNEL_PER_TYPE` ASC) VISIBLE,
  INDEX `fk_POS_BARTENDER1_idx` (`BARTENDER_PERSONNEL_PER_TYPE` ASC) VISIBLE,
  INDEX `fk_POS_PRINT_INVOICE1_idx` (`PRINT_INVOICE_INVOICE_ID` ASC) VISIBLE,
  CONSTRAINT `fk_POS_CUSTOMER(S)1`
    FOREIGN KEY (`CUSTOMER(S)_PERSONNEL_PER_TYPE`)
    REFERENCES `POS_SYSTEM`.`CUSTOMER(S)` (`PERSONNEL_PER_TYPE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_POS_BARTENDER1`
    FOREIGN KEY (`BARTENDER_PERSONNEL_PER_TYPE`)
    REFERENCES `POS_SYSTEM`.`BARTENDER` (`PERSONNEL_PER_TYPE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_POS_PRINT_INVOICE1`
    FOREIGN KEY (`PRINT_INVOICE_INVOICE_ID`)
    REFERENCES `POS_SYSTEM`.`PRINT_INVOICE` (`INVOICE_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `POS_SYSTEM`.`MANAGER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `POS_SYSTEM`.`MANAGER` (
  `MANAGER_DESC` VARCHAR(45) NOT NULL,
  `PERSONNEL_PER_TYPE` INT NOT NULL,
  PRIMARY KEY (`PERSONNEL_PER_TYPE`),
  CONSTRAINT `fk_MANAGER_PERSONNEL1`
    FOREIGN KEY (`PERSONNEL_PER_TYPE`)
    REFERENCES `POS_SYSTEM`.`PERSONNEL` (`PER_TYPE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `POS_SYSTEM`.`SALARY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `POS_SYSTEM`.`SALARY` (
  `SALARY_ID` INT NOT NULL,
  `SALARY_EMP` VARCHAR(45) NOT NULL,
  `SALARY_HOURS` DATETIME NOT NULL,
  `SALARY_DATE` TIME NOT NULL,
  `MANAGER_PERSONNEL_PER_TYPE` INT NOT NULL,
  `POS_POS_ID` INT NOT NULL,
  `POS_BAR_PRODUCTS_DRINK_ID` INT NOT NULL,
  `POS_CUSTOMER(S)_PERSONNEL_PER_TYPE` INT NOT NULL,
  `POS_BARTENDER_PERSONNEL_PER_TYPE` INT NOT NULL,
  `POS_PRINT_INVOICE_INVOICE_ID` INT NOT NULL,
  PRIMARY KEY (`SALARY_ID`, `MANAGER_PERSONNEL_PER_TYPE`, `POS_POS_ID`, `POS_BAR_PRODUCTS_DRINK_ID`, `POS_CUSTOMER(S)_PERSONNEL_PER_TYPE`, `POS_BARTENDER_PERSONNEL_PER_TYPE`, `POS_PRINT_INVOICE_INVOICE_ID`),
  INDEX `fk_SALARY_MANAGER1_idx` (`MANAGER_PERSONNEL_PER_TYPE` ASC) VISIBLE,
  INDEX `fk_SALARY_POS1_idx` (`POS_POS_ID` ASC, `POS_BAR_PRODUCTS_DRINK_ID` ASC, `POS_CUSTOMER(S)_PERSONNEL_PER_TYPE` ASC, `POS_BARTENDER_PERSONNEL_PER_TYPE` ASC, `POS_PRINT_INVOICE_INVOICE_ID` ASC) VISIBLE,
  CONSTRAINT `fk_SALARY_MANAGER1`
    FOREIGN KEY (`MANAGER_PERSONNEL_PER_TYPE`)
    REFERENCES `POS_SYSTEM`.`MANAGER` (`PERSONNEL_PER_TYPE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SALARY_POS1`
    FOREIGN KEY (`POS_POS_ID` , `POS_BAR_PRODUCTS_DRINK_ID` , `POS_CUSTOMER(S)_PERSONNEL_PER_TYPE` , `POS_BARTENDER_PERSONNEL_PER_TYPE` , `POS_PRINT_INVOICE_INVOICE_ID`)
    REFERENCES `POS_SYSTEM`.`POS` (`POS_ID` , `BAR_PRODUCTS_DRINK_ID` , `CUSTOMER(S)_PERSONNEL_PER_TYPE` , `BARTENDER_PERSONNEL_PER_TYPE` , `PRINT_INVOICE_INVOICE_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
